// Code generated by Kitex v0.5.1. DO NOT EDIT.
package service

import (
	server "github.com/cloudwego/kitex/server"
	user "github.com/pkuphysu/meetplan/kitex_gen/pkuphy/meetplan/user"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler user.Service, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
