// Code generated by Validator v0.1.4. DO NOT EDIT.

package plan

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Plan) IsValid() error {
	if p.Id != nil {
		if *p.Id < int64(1) {
			return fmt.Errorf("field Id ge rule failed, current value: %v", *p.Id)
		}
	}
	if p.TeacherId != nil {
		if *p.TeacherId < int64(1) {
			return fmt.Errorf("field TeacherId ge rule failed, current value: %v", *p.TeacherId)
		}
	}
	if p.StartTime != nil {
		if *p.StartTime < int64(946684800) {
			return fmt.Errorf("field StartTime ge rule failed, current value: %v", *p.StartTime)
		}
	}
	if p.Duration != nil {
		if *p.Duration < int64(1800) {
			return fmt.Errorf("field Duration ge rule failed, current value: %v", *p.Duration)
		}
	}
	if p.Quota != nil {
		_src := []int8{int8(1), int8(2)}
		var _exist bool
		for _, src := range _src {
			if *p.Quota == int8(src) {
				_exist = true
				break
			}
		}
		if !_exist {
			return fmt.Errorf("field Quota in rule failed, current value: %v", *p.Quota)
		}
	}
	if p.RemainingQuota != nil {
		if *p.RemainingQuota < int8(0) {
			return fmt.Errorf("field RemainingQuota ge rule failed, current value: %v", *p.RemainingQuota)
		}
		if *p.RemainingQuota > int8(*p.Quota) {
			return fmt.Errorf("field RemainingQuota le rule failed, current value: %v", *p.RemainingQuota)
		}
	}
	return nil
}
func (p *GetPlanReq) IsValid() error {
	return nil
}
func (p *GetPlanResp) IsValid() error {
	if p.Plan != nil {
		if err := p.Plan.IsValid(); err != nil {
			return fmt.Errorf("filed Plan not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *MGetPlanReq) IsValid() error {
	if len(p.IdList) < int(1) {
		return fmt.Errorf("field IdList MinLen rule failed, current value: %v", p.IdList)
	}
	return nil
}
func (p *MGetPlanResp) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *QueryPlanReq) IsValid() error {
	if p.PageParam != nil {
		if err := p.PageParam.IsValid(); err != nil {
			return fmt.Errorf("filed PageParam not valid, %w", err)
		}
	}
	return nil
}
func (p *QueryPlanResp) IsValid() error {
	if p.PageParam != nil {
		if err := p.PageParam.IsValid(); err != nil {
			return fmt.Errorf("filed PageParam not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *CreatePlanReq) IsValid() error {
	if p.Plan == nil {
		return fmt.Errorf("field Plan not_nil rule failed")
	}
	if err := p.Plan.IsValid(); err != nil {
		return fmt.Errorf("filed Plan not valid, %w", err)
	}
	return nil
}
func (p *CreatePlanResp) IsValid() error {
	if p.Plan != nil {
		if err := p.Plan.IsValid(); err != nil {
			return fmt.Errorf("filed Plan not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *MCreatePlanReq) IsValid() error {
	return nil
}
func (p *MCreatePlanResp) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
