// Code generated by hertz generator.

package meetplan

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmeetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemeetplansMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmeetplanandorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmeetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemeetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemeetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meetplan0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeetplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _order0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getselfMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendlinkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createfriendlinkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetermdaterangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettermdaterangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createupdaterecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listupdaterecordMw() []app.HandlerFunc {
	// your code...
	return nil
}
