# Generated by Django 3.1 on 2020-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('app', models.CharField(max_length=32, verbose_name='应用')),
                ('name', models.CharField(max_length=128, verbose_name='属性')),
                ('value', models.TextField(verbose_name='值')),
            ],
            options={
                'verbose_name': '设置',
                'verbose_name_plural': '设置',
                'unique_together': {('app', 'name')},
            },
        ),
    ]
