// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/datatypes"
)

const TableNameOption = "options"

// Option mapped from table <options>
type Option struct {
	ID    int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string         `gorm:"column:name;not null" json:"name"`
	Value datatypes.JSON `gorm:"column:value;not null" json:"value"`
}

// TableName Option's table name
func (*Option) TableName() string {
	return TableNameOption
}
