// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm_gen

import (
	"time"
)

const TableNamePlan = "plans"

// Plan mapped from table <plans>
type Plan struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeacherID int64     `gorm:"column:teacher_id;not null" json:"teacher_id"`
	StartTime time.Time `gorm:"column:start_time;not null" json:"start_time"`
	Duration  int64     `gorm:"column:duration;not null" json:"duration"`
	Place     string    `gorm:"column:place;not null" json:"place"`
	Quota     int8      `gorm:"column:quota;not null" json:"quota"`
	Message   *string   `gorm:"column:message" json:"message"`
	Orders    []*Order  `json:"orders"`
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
