// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/logger/accesslog"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/requestid"

	"meetplan/biz/dal"
	"meetplan/biz/dal/mysql"
	"meetplan/biz/gorm_gen/query"
	"meetplan/config"
	"meetplan/internal/oidc_rp"
)

func main() {
	dal.Init()
	query.SetDefault(mysql.DB)
	oidc_rp.GetProvider()

	conf := config.GetConf()
	h := server.Default(server.WithHostPorts(conf.Hertz.Address))
	if conf.Hertz.EnablePprof {
		pprof.Register(h)
	}
	h.Use(accesslog.New(), cors.New(cors.Config{
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Length", "Content-Type", "Authorization"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
		AllowAllOrigins:  true,
	}), requestid.New())
	register(h)

	h.Spin()
	dal.Close()
}
