// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	pkuphy_meetplan "github.com/pkuphysu/meetplan/cmd/api/biz/router/pkuphy_meetplan"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pkuphy_meetplan.Register(r)
}
