// Code generated by Kitex v0.5.1. DO NOT EDIT.

package service

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	order "github.com/pkuphysu/meetplan/kitex_gen/pkuphy/meetplan/order"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetOrder(ctx context.Context, req *order.GetOrderReq, callOptions ...callopt.Option) (r *order.GetOrderResp, err error)
	MGetOrder(ctx context.Context, req *order.MGetOrderReq, callOptions ...callopt.Option) (r *order.MGetOrderResp, err error)
	QueryOrder(ctx context.Context, req *order.QueryOrderReq, callOptions ...callopt.Option) (r *order.QueryOrderResp, err error)
	CreateOrder(ctx context.Context, req *order.CreateOrderReq, callOptions ...callopt.Option) (r *order.CreateOrderResp, err error)
	MCreateOrder(ctx context.Context, req *order.MCreateOrderReq, callOptions ...callopt.Option) (r *order.MCreateOrderResp, err error)
	UpdateOrder(ctx context.Context, req *order.UpdateOrderReq, callOptions ...callopt.Option) (r *order.UpdateOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kServiceClient struct {
	*kClient
}

func (p *kServiceClient) GetOrder(ctx context.Context, req *order.GetOrderReq, callOptions ...callopt.Option) (r *order.GetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, req)
}

func (p *kServiceClient) MGetOrder(ctx context.Context, req *order.MGetOrderReq, callOptions ...callopt.Option) (r *order.MGetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetOrder(ctx, req)
}

func (p *kServiceClient) QueryOrder(ctx context.Context, req *order.QueryOrderReq, callOptions ...callopt.Option) (r *order.QueryOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrder(ctx, req)
}

func (p *kServiceClient) CreateOrder(ctx context.Context, req *order.CreateOrderReq, callOptions ...callopt.Option) (r *order.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kServiceClient) MCreateOrder(ctx context.Context, req *order.MCreateOrderReq, callOptions ...callopt.Option) (r *order.MCreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MCreateOrder(ctx, req)
}

func (p *kServiceClient) UpdateOrder(ctx context.Context, req *order.UpdateOrderReq, callOptions ...callopt.Option) (r *order.UpdateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrder(ctx, req)
}
