// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pkuphysu/meetplan/cmd/api/biz/model/api"
)

// Ping .
// @router /hello [GET]
func Ping(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PingResponse)

	c.JSON(consts.StatusOK, resp)
}
