// Code generated by hertz generator.

package meetplan

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "meetplan/cmd/api/biz/model"
)

// GetMeetPlan .
// @router /api/v1/meetplan/:id [GET]
func GetMeetPlan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.GetMeetPlanRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.GetMeetPlanResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListMeetPlan .
// @router /api/v1/meetplan [GET]
func ListMeetPlan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.ListMeetPlanRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.ListMeetPlanResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateMeetPlan .
// @router /api/v1/meetplan [POST]
func CreateMeetPlan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.CreateMeetPlanRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.CreateMeetPlanResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateMeetPlan .
// @router /api/v1/meetplan/:id [PUT]
func UpdateMeetPlan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.UpdateMeetPlanRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.UpdateMeetPlanResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteMeetPlan .
// @router /api/v1/meetplan/:id [DELETE]
func DeleteMeetPlan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.DeleteMeetPlanRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.DeleteMeetPlanResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteMeetPlans .
// @router /api/v1/meetplan [DELETE]
func DeleteMeetPlans(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.DeleteMeetPlansRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.DeleteMeetPlansResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetOrder .
// @router /api/v1/order/:id [GET]
func GetOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.GetOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.GetOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListOrder .
// @router /api/v1/order [GET]
func ListOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.ListOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.ListOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateOrder .
// @router /api/v1/order [POST]
func CreateOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.CreateOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.CreateOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateOrder .
// @router /api/v1/order/:id [PUT]
func UpdateOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.UpdateOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.UpdateOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateMeetPlanAndOrder .
// @router /api/v1/meetplanorder [POST]
func CreateMeetPlanAndOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.CreateMeetPlanAndOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.CreateMeetPlanAndOrderResponse)

	c.JSON(consts.StatusOK, resp)
}
