# Generated by Django 2.2.10 on 2020-04-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('app', models.CharField(db_index=True, max_length=32, verbose_name='应用名')),
                ('upload_or_generate', models.BooleanField(choices=[(True, '上传'), (False, '生成')], default=True, verbose_name='上传还是生成')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '图片管理',
                'verbose_name_plural': '图片管理',
            },
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('app', models.CharField(db_index=True, max_length=32, verbose_name='应用名')),
                ('upload_or_generate', models.BooleanField(choices=[(True, '上传'), (False, '生成')], default=True, verbose_name='上传还是生成')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
            },
        ),
    ]
