// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: http/model/meetplan.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "meetplan/cmd/api/biz/model/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_CREATED  OrderStatus = 0
	OrderStatus_FINISHED OrderStatus = 1
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "CREATED",
		1: "FINISHED",
	}
	OrderStatus_value = map[string]int32{
		"CREATED":  0,
		"FINISHED": 1,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_http_model_meetplan_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_http_model_meetplan_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{0}
}

type MeetPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	TeacherId int64    `protobuf:"varint,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty" form:"teacher_id" query:"teacher_id"`
	StartTime int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" form:"start_time" query:"start_time"`
	Duration  int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty" form:"duration" query:"duration"`
	Place     string   `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty" form:"place" query:"place"`
	Message   string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Quota     int32    `protobuf:"varint,7,opt,name=quota,proto3" json:"quota,omitempty" form:"quota" query:"quota"`
	Teacher   *User    `protobuf:"bytes,8,opt,name=teacher,proto3" json:"teacher,omitempty" form:"teacher" query:"teacher"`
	Orders    []*Order `protobuf:"bytes,9,rep,name=orders,proto3" json:"orders,omitempty" form:"orders" query:"orders"`
}

func (x *MeetPlan) Reset() {
	*x = MeetPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeetPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetPlan) ProtoMessage() {}

func (x *MeetPlan) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetPlan.ProtoReflect.Descriptor instead.
func (*MeetPlan) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{0}
}

func (x *MeetPlan) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MeetPlan) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *MeetPlan) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MeetPlan) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MeetPlan) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *MeetPlan) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MeetPlan) GetQuota() int32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *MeetPlan) GetTeacher() *User {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *MeetPlan) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	MeetPlanId int64       `protobuf:"varint,2,opt,name=meet_plan_id,json=meetPlanId,proto3" json:"meet_plan_id,omitempty" form:"meet_plan_id" query:"meet_plan_id"`
	StudentId  int64       `protobuf:"varint,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty" form:"student_id" query:"student_id"`
	Message    string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Status     OrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=model.OrderStatus" json:"status,omitempty" form:"status" query:"status"`
	MeetPlan   *MeetPlan   `protobuf:"bytes,6,opt,name=meet_plan,json=meetPlan,proto3" json:"meet_plan,omitempty" form:"meet_plan" query:"meet_plan"`
	Student    *User       `protobuf:"bytes,7,opt,name=student,proto3" json:"student,omitempty" form:"student" query:"student"`
	Teacher    *User       `protobuf:"bytes,8,opt,name=teacher,proto3" json:"teacher,omitempty" form:"teacher" query:"teacher"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetMeetPlanId() int64 {
	if x != nil {
		return x.MeetPlanId
	}
	return 0
}

func (x *Order) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *Order) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

func (x *Order) GetMeetPlan() *MeetPlan {
	if x != nil {
		return x.MeetPlan
	}
	return nil
}

func (x *Order) GetStudent() *User {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *Order) GetTeacher() *User {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type GetMeetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	WithTeacher  bool  `protobuf:"varint,2,opt,name=with_teacher,json=withTeacher,proto3" json:"with_teacher,omitempty" form:"with_teacher" query:"with_teacher"`
	WithOrders   bool  `protobuf:"varint,3,opt,name=with_orders,json=withOrders,proto3" json:"with_orders,omitempty" form:"with_orders" query:"with_orders"`
	WithStudents bool  `protobuf:"varint,4,opt,name=with_students,json=withStudents,proto3" json:"with_students,omitempty" form:"with_students" query:"with_students"`
}

func (x *GetMeetPlanRequest) Reset() {
	*x = GetMeetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetPlanRequest) ProtoMessage() {}

func (x *GetMeetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetMeetPlanRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{2}
}

func (x *GetMeetPlanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMeetPlanRequest) GetWithTeacher() bool {
	if x != nil {
		return x.WithTeacher
	}
	return false
}

func (x *GetMeetPlanRequest) GetWithOrders() bool {
	if x != nil {
		return x.WithOrders
	}
	return false
}

func (x *GetMeetPlanRequest) GetWithStudents() bool {
	if x != nil {
		return x.WithStudents
	}
	return false
}

type GetMeetPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message  string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	MeetPlan *MeetPlan `protobuf:"bytes,3,opt,name=meet_plan,json=meetPlan,proto3" json:"meet_plan,omitempty" form:"meet_plan" query:"meet_plan"`
}

func (x *GetMeetPlanResponse) Reset() {
	*x = GetMeetPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetPlanResponse) ProtoMessage() {}

func (x *GetMeetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetMeetPlanResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{3}
}

func (x *GetMeetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMeetPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMeetPlanResponse) GetMeetPlan() *MeetPlan {
	if x != nil {
		return x.MeetPlan
	}
	return nil
}

type ListMeetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           []int64         `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	TeacherId    []int64         `protobuf:"varint,2,rep,packed,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty" form:"teacher_id" query:"teacher_id"`
	StartTimeGe  int64           `protobuf:"varint,3,opt,name=start_time_ge,json=startTimeGe,proto3" json:"start_time_ge,omitempty" form:"start_time_ge" query:"start_time_ge"`
	StudentId    []int64         `protobuf:"varint,4,rep,packed,name=student_id,json=studentId,proto3" json:"student_id,omitempty" form:"student_id" query:"student_id"`
	WithTeacher  bool            `protobuf:"varint,5,opt,name=with_teacher,json=withTeacher,proto3" json:"with_teacher,omitempty" form:"with_teacher" query:"with_teacher"`
	WithOrders   bool            `protobuf:"varint,6,opt,name=with_orders,json=withOrders,proto3" json:"with_orders,omitempty" form:"with_orders" query:"with_orders"`
	WithStudents bool            `protobuf:"varint,7,opt,name=with_students,json=withStudents,proto3" json:"with_students,omitempty" form:"with_students" query:"with_students"`
	PageParam    *QueryPageParam `protobuf:"bytes,8,opt,name=page_param,json=pageParam,proto3" json:"page_param,omitempty" form:"page_param" query:"page_param"`
}

func (x *ListMeetPlanRequest) Reset() {
	*x = ListMeetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMeetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetPlanRequest) ProtoMessage() {}

func (x *ListMeetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetPlanRequest.ProtoReflect.Descriptor instead.
func (*ListMeetPlanRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{4}
}

func (x *ListMeetPlanRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListMeetPlanRequest) GetTeacherId() []int64 {
	if x != nil {
		return x.TeacherId
	}
	return nil
}

func (x *ListMeetPlanRequest) GetStartTimeGe() int64 {
	if x != nil {
		return x.StartTimeGe
	}
	return 0
}

func (x *ListMeetPlanRequest) GetStudentId() []int64 {
	if x != nil {
		return x.StudentId
	}
	return nil
}

func (x *ListMeetPlanRequest) GetWithTeacher() bool {
	if x != nil {
		return x.WithTeacher
	}
	return false
}

func (x *ListMeetPlanRequest) GetWithOrders() bool {
	if x != nil {
		return x.WithOrders
	}
	return false
}

func (x *ListMeetPlanRequest) GetWithStudents() bool {
	if x != nil {
		return x.WithStudents
	}
	return false
}

func (x *ListMeetPlanRequest) GetPageParam() *QueryPageParam {
	if x != nil {
		return x.PageParam
	}
	return nil
}

type ListMeetPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message   string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	MeetPlans []*MeetPlan `protobuf:"bytes,3,rep,name=meet_plans,json=meetPlans,proto3" json:"meet_plans,omitempty" form:"meet_plans" query:"meet_plans"`
	PageParam *Pagination `protobuf:"bytes,4,opt,name=page_param,json=pageParam,proto3" json:"page_param,omitempty" form:"page_param" query:"page_param"`
}

func (x *ListMeetPlanResponse) Reset() {
	*x = ListMeetPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMeetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetPlanResponse) ProtoMessage() {}

func (x *ListMeetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetPlanResponse.ProtoReflect.Descriptor instead.
func (*ListMeetPlanResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{5}
}

func (x *ListMeetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListMeetPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListMeetPlanResponse) GetMeetPlans() []*MeetPlan {
	if x != nil {
		return x.MeetPlans
	}
	return nil
}

func (x *ListMeetPlanResponse) GetPageParam() *Pagination {
	if x != nil {
		return x.PageParam
	}
	return nil
}

type CreateMeetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherId int64  `protobuf:"varint,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty" form:"teacher_id" query:"teacher_id"`
	StartTime int64  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" form:"start_time" query:"start_time"`
	Duration  int64  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty" form:"duration" query:"duration"`
	Place     string `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty" form:"place" query:"place"`
	Message   string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Quota     int32  `protobuf:"varint,6,opt,name=quota,proto3" json:"quota,omitempty" form:"quota" query:"quota"`
}

func (x *CreateMeetPlanRequest) Reset() {
	*x = CreateMeetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetPlanRequest) ProtoMessage() {}

func (x *CreateMeetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetPlanRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMeetPlanRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CreateMeetPlanRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateMeetPlanRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateMeetPlanRequest) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *CreateMeetPlanRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMeetPlanRequest) GetQuota() int32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

type CreateMeetPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message  string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	MeetPlan *MeetPlan `protobuf:"bytes,3,opt,name=meet_plan,json=meetPlan,proto3" json:"meet_plan,omitempty" form:"meet_plan" query:"meet_plan"`
}

func (x *CreateMeetPlanResponse) Reset() {
	*x = CreateMeetPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetPlanResponse) ProtoMessage() {}

func (x *CreateMeetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetPlanResponse.ProtoReflect.Descriptor instead.
func (*CreateMeetPlanResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMeetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateMeetPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMeetPlanResponse) GetMeetPlan() *MeetPlan {
	if x != nil {
		return x.MeetPlan
	}
	return nil
}

type UpdateMeetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	StartTime int64  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" form:"start_time" query:"start_time"`
	Duration  int64  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty" form:"duration" query:"duration"`
	Place     string `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty" form:"place" query:"place"`
	Message   string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Quota     int32  `protobuf:"varint,7,opt,name=quota,proto3" json:"quota,omitempty" form:"quota" query:"quota"`
}

func (x *UpdateMeetPlanRequest) Reset() {
	*x = UpdateMeetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMeetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetPlanRequest) ProtoMessage() {}

func (x *UpdateMeetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetPlanRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeetPlanRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMeetPlanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMeetPlanRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateMeetPlanRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateMeetPlanRequest) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *UpdateMeetPlanRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMeetPlanRequest) GetQuota() int32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

type UpdateMeetPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message  string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	MeetPlan *MeetPlan `protobuf:"bytes,3,opt,name=meet_plan,json=meetPlan,proto3" json:"meet_plan,omitempty" form:"meet_plan" query:"meet_plan"`
}

func (x *UpdateMeetPlanResponse) Reset() {
	*x = UpdateMeetPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMeetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetPlanResponse) ProtoMessage() {}

func (x *UpdateMeetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetPlanResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeetPlanResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMeetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateMeetPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMeetPlanResponse) GetMeetPlan() *MeetPlan {
	if x != nil {
		return x.MeetPlan
	}
	return nil
}

type DeleteMeetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
}

func (x *DeleteMeetPlanRequest) Reset() {
	*x = DeleteMeetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetPlanRequest) ProtoMessage() {}

func (x *DeleteMeetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetPlanRequest.ProtoReflect.Descriptor instead.
func (*DeleteMeetPlanRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMeetPlanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMeetPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
}

func (x *DeleteMeetPlanResponse) Reset() {
	*x = DeleteMeetPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetPlanResponse) ProtoMessage() {}

func (x *DeleteMeetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetPlanResponse.ProtoReflect.Descriptor instead.
func (*DeleteMeetPlanResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMeetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteMeetPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteMeetPlansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty" form:"ids" query:"ids"`
}

func (x *DeleteMeetPlansRequest) Reset() {
	*x = DeleteMeetPlansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetPlansRequest) ProtoMessage() {}

func (x *DeleteMeetPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetPlansRequest.ProtoReflect.Descriptor instead.
func (*DeleteMeetPlansRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMeetPlansRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteMeetPlansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
}

func (x *DeleteMeetPlansResponse) Reset() {
	*x = DeleteMeetPlansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetPlansResponse) ProtoMessage() {}

func (x *DeleteMeetPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetPlansResponse.ProtoReflect.Descriptor instead.
func (*DeleteMeetPlansResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMeetPlansResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteMeetPlansResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	WithMeetPlan bool  `protobuf:"varint,2,opt,name=with_meet_plan,json=withMeetPlan,proto3" json:"with_meet_plan,omitempty" form:"with_meet_plan" query:"with_meet_plan"`
	WithStudent  bool  `protobuf:"varint,3,opt,name=with_student,json=withStudent,proto3" json:"with_student,omitempty" form:"with_student" query:"with_student"`
	WithTeacher  bool  `protobuf:"varint,4,opt,name=with_teacher,json=withTeacher,proto3" json:"with_teacher,omitempty" form:"with_teacher" query:"with_teacher"`
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderRequest) GetWithMeetPlan() bool {
	if x != nil {
		return x.WithMeetPlan
	}
	return false
}

func (x *GetOrderRequest) GetWithStudent() bool {
	if x != nil {
		return x.WithStudent
	}
	return false
}

func (x *GetOrderRequest) GetWithTeacher() bool {
	if x != nil {
		return x.WithTeacher
	}
	return false
}

type GetOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Order   *Order `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty" form:"order" query:"order"`
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           []int64         `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	MeetPlanId   []int64         `protobuf:"varint,2,rep,packed,name=meet_plan_id,json=meetPlanId,proto3" json:"meet_plan_id,omitempty" form:"meet_plan_id" query:"meet_plan_id"`
	StudentId    []int64         `protobuf:"varint,3,rep,packed,name=student_id,json=studentId,proto3" json:"student_id,omitempty" form:"student_id" query:"student_id"`
	Status       OrderStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=model.OrderStatus" json:"status,omitempty" form:"status" query:"status"`
	WithMeetPlan bool            `protobuf:"varint,5,opt,name=with_meet_plan,json=withMeetPlan,proto3" json:"with_meet_plan,omitempty" form:"with_meet_plan" query:"with_meet_plan"`
	WithStudent  bool            `protobuf:"varint,6,opt,name=with_student,json=withStudent,proto3" json:"with_student,omitempty" form:"with_student" query:"with_student"`
	WithTeacher  bool            `protobuf:"varint,7,opt,name=with_teacher,json=withTeacher,proto3" json:"with_teacher,omitempty" form:"with_teacher" query:"with_teacher"`
	PageParam    *QueryPageParam `protobuf:"bytes,8,opt,name=page_param,json=pageParam,proto3" json:"page_param,omitempty" form:"page_param" query:"page_param"`
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{16}
}

func (x *ListOrderRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListOrderRequest) GetMeetPlanId() []int64 {
	if x != nil {
		return x.MeetPlanId
	}
	return nil
}

func (x *ListOrderRequest) GetStudentId() []int64 {
	if x != nil {
		return x.StudentId
	}
	return nil
}

func (x *ListOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

func (x *ListOrderRequest) GetWithMeetPlan() bool {
	if x != nil {
		return x.WithMeetPlan
	}
	return false
}

func (x *ListOrderRequest) GetWithStudent() bool {
	if x != nil {
		return x.WithStudent
	}
	return false
}

func (x *ListOrderRequest) GetWithTeacher() bool {
	if x != nil {
		return x.WithTeacher
	}
	return false
}

func (x *ListOrderRequest) GetPageParam() *QueryPageParam {
	if x != nil {
		return x.PageParam
	}
	return nil
}

type ListOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message   string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Orders    []*Order    `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty" form:"orders" query:"orders"`
	PageParam *Pagination `protobuf:"bytes,4,opt,name=page_param,json=pageParam,proto3" json:"page_param,omitempty" form:"page_param" query:"page_param"`
}

func (x *ListOrderResponse) Reset() {
	*x = ListOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponse) ProtoMessage() {}

func (x *ListOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponse.ProtoReflect.Descriptor instead.
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{17}
}

func (x *ListOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListOrderResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrderResponse) GetPageParam() *Pagination {
	if x != nil {
		return x.PageParam
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetPlanId int64  `protobuf:"varint,1,opt,name=meet_plan_id,json=meetPlanId,proto3" json:"meet_plan_id,omitempty" form:"meet_plan_id" query:"meet_plan_id"`
	StudentId  int64  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty" form:"student_id" query:"student_id"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{18}
}

func (x *CreateOrderRequest) GetMeetPlanId() int64 {
	if x != nil {
		return x.MeetPlanId
	}
	return 0
}

func (x *CreateOrderRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CreateOrderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Order   *Order `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty" form:"order" query:"order"`
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{19}
}

func (x *CreateOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Status  OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=model.OrderStatus" json:"status,omitempty" form:"status" query:"status"`
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

type UpdateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Order   *Order `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty" form:"order" query:"order"`
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateMeetPlanAndOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherId int64    `protobuf:"varint,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty" form:"teacher_id" query:"teacher_id"`
	StartTime int64    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" form:"start_time" query:"start_time"`
	Duration  int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty" form:"duration" query:"duration"`
	Place     string   `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty" form:"place" query:"place"`
	Message   string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	Quota     int32    `protobuf:"varint,6,opt,name=quota,proto3" json:"quota,omitempty" form:"quota" query:"quota"`
	Orders    []*Order `protobuf:"bytes,7,rep,name=orders,proto3" json:"orders,omitempty" form:"orders" query:"orders"`
}

func (x *CreateMeetPlanAndOrderRequest) Reset() {
	*x = CreateMeetPlanAndOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetPlanAndOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetPlanAndOrderRequest) ProtoMessage() {}

func (x *CreateMeetPlanAndOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetPlanAndOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetPlanAndOrderRequest) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{22}
}

func (x *CreateMeetPlanAndOrderRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CreateMeetPlanAndOrderRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateMeetPlanAndOrderRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateMeetPlanAndOrderRequest) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *CreateMeetPlanAndOrderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMeetPlanAndOrderRequest) GetQuota() int32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *CreateMeetPlanAndOrderRequest) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CreateMeetPlanAndOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" query:"code"`
	Message  string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
	MeetPlan *MeetPlan `protobuf:"bytes,3,opt,name=meet_plan,json=meetPlan,proto3" json:"meet_plan,omitempty" form:"meet_plan" query:"meet_plan"`
}

func (x *CreateMeetPlanAndOrderResponse) Reset() {
	*x = CreateMeetPlanAndOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_model_meetplan_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetPlanAndOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetPlanAndOrderResponse) ProtoMessage() {}

func (x *CreateMeetPlanAndOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_meetplan_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetPlanAndOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateMeetPlanAndOrderResponse) Descriptor() ([]byte, []int) {
	return file_http_model_meetplan_proto_rawDescGZIP(), []int{23}
}

func (x *CreateMeetPlanAndOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateMeetPlanAndOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMeetPlanAndOrderResponse) GetMeetPlan() *MeetPlan {
	if x != nil {
		return x.MeetPlan
	}
	return nil
}

var File_http_model_meetplan_proto protoreflect.FileDescriptor

var file_http_model_meetplan_proto_rawDesc = []byte{
	0x0a, 0x19, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x65, 0x65,
	0x74, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x15, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x15, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02, 0x0a, 0x08, 0x4d, 0x65,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x22, 0x9a, 0x02, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0c, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x74, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x22, 0x95, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x77, 0x69, 0x74, 0x68,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x71, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a,
	0x09, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x08, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x22, 0xa6, 0x02, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x47, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x74,
	0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x77,
	0x69, 0x74, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x34,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x6d,
	0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0xb7, 0x01,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x74, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x22, 0xb0, 0x01,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x6f, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x22, 0x74, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x08, 0x6d, 0x65,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18,
	0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x2a, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c,
	0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x4d, 0x65,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69,
	0x74, 0x68, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x77, 0x69, 0x74, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0xb1, 0x02, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x65, 0x65, 0x74, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6d,
	0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x65,
	0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x77, 0x69,
	0x74, 0x68, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69,
	0x74, 0x68, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x12, 0x34, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x30, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x22, 0x6f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x65, 0x65, 0x74,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x67, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x72, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06,
	0xd2, 0xbb, 0x18, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x67, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xe5, 0x01, 0x0a, 0x1d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x41, 0x6e, 0x64, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x22, 0x7c, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x6e, 0x41, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x2a,
	0x28, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x65, 0x65,
	0x74, 0x70, 0x6c, 0x61, 0x6e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69,
	0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_model_meetplan_proto_rawDescOnce sync.Once
	file_http_model_meetplan_proto_rawDescData = file_http_model_meetplan_proto_rawDesc
)

func file_http_model_meetplan_proto_rawDescGZIP() []byte {
	file_http_model_meetplan_proto_rawDescOnce.Do(func() {
		file_http_model_meetplan_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_model_meetplan_proto_rawDescData)
	})
	return file_http_model_meetplan_proto_rawDescData
}

var file_http_model_meetplan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_http_model_meetplan_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_http_model_meetplan_proto_goTypes = []interface{}{
	(OrderStatus)(0),                       // 0: model.OrderStatus
	(*MeetPlan)(nil),                       // 1: model.MeetPlan
	(*Order)(nil),                          // 2: model.Order
	(*GetMeetPlanRequest)(nil),             // 3: model.GetMeetPlanRequest
	(*GetMeetPlanResponse)(nil),            // 4: model.GetMeetPlanResponse
	(*ListMeetPlanRequest)(nil),            // 5: model.ListMeetPlanRequest
	(*ListMeetPlanResponse)(nil),           // 6: model.ListMeetPlanResponse
	(*CreateMeetPlanRequest)(nil),          // 7: model.CreateMeetPlanRequest
	(*CreateMeetPlanResponse)(nil),         // 8: model.CreateMeetPlanResponse
	(*UpdateMeetPlanRequest)(nil),          // 9: model.UpdateMeetPlanRequest
	(*UpdateMeetPlanResponse)(nil),         // 10: model.UpdateMeetPlanResponse
	(*DeleteMeetPlanRequest)(nil),          // 11: model.DeleteMeetPlanRequest
	(*DeleteMeetPlanResponse)(nil),         // 12: model.DeleteMeetPlanResponse
	(*DeleteMeetPlansRequest)(nil),         // 13: model.DeleteMeetPlansRequest
	(*DeleteMeetPlansResponse)(nil),        // 14: model.DeleteMeetPlansResponse
	(*GetOrderRequest)(nil),                // 15: model.GetOrderRequest
	(*GetOrderResponse)(nil),               // 16: model.GetOrderResponse
	(*ListOrderRequest)(nil),               // 17: model.ListOrderRequest
	(*ListOrderResponse)(nil),              // 18: model.ListOrderResponse
	(*CreateOrderRequest)(nil),             // 19: model.CreateOrderRequest
	(*CreateOrderResponse)(nil),            // 20: model.CreateOrderResponse
	(*UpdateOrderRequest)(nil),             // 21: model.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),            // 22: model.UpdateOrderResponse
	(*CreateMeetPlanAndOrderRequest)(nil),  // 23: model.CreateMeetPlanAndOrderRequest
	(*CreateMeetPlanAndOrderResponse)(nil), // 24: model.CreateMeetPlanAndOrderResponse
	(*User)(nil),                           // 25: model.User
	(*QueryPageParam)(nil),                 // 26: model.QueryPageParam
	(*Pagination)(nil),                     // 27: model.Pagination
}
var file_http_model_meetplan_proto_depIdxs = []int32{
	25, // 0: model.MeetPlan.teacher:type_name -> model.User
	2,  // 1: model.MeetPlan.orders:type_name -> model.Order
	0,  // 2: model.Order.status:type_name -> model.OrderStatus
	1,  // 3: model.Order.meet_plan:type_name -> model.MeetPlan
	25, // 4: model.Order.student:type_name -> model.User
	25, // 5: model.Order.teacher:type_name -> model.User
	1,  // 6: model.GetMeetPlanResponse.meet_plan:type_name -> model.MeetPlan
	26, // 7: model.ListMeetPlanRequest.page_param:type_name -> model.QueryPageParam
	1,  // 8: model.ListMeetPlanResponse.meet_plans:type_name -> model.MeetPlan
	27, // 9: model.ListMeetPlanResponse.page_param:type_name -> model.Pagination
	1,  // 10: model.CreateMeetPlanResponse.meet_plan:type_name -> model.MeetPlan
	1,  // 11: model.UpdateMeetPlanResponse.meet_plan:type_name -> model.MeetPlan
	2,  // 12: model.GetOrderResponse.order:type_name -> model.Order
	0,  // 13: model.ListOrderRequest.status:type_name -> model.OrderStatus
	26, // 14: model.ListOrderRequest.page_param:type_name -> model.QueryPageParam
	2,  // 15: model.ListOrderResponse.orders:type_name -> model.Order
	27, // 16: model.ListOrderResponse.page_param:type_name -> model.Pagination
	2,  // 17: model.CreateOrderResponse.order:type_name -> model.Order
	0,  // 18: model.UpdateOrderRequest.status:type_name -> model.OrderStatus
	2,  // 19: model.UpdateOrderResponse.order:type_name -> model.Order
	2,  // 20: model.CreateMeetPlanAndOrderRequest.orders:type_name -> model.Order
	1,  // 21: model.CreateMeetPlanAndOrderResponse.meet_plan:type_name -> model.MeetPlan
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_http_model_meetplan_proto_init() }
func file_http_model_meetplan_proto_init() {
	if File_http_model_meetplan_proto != nil {
		return
	}
	file_http_model_common_proto_init()
	file_http_model_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_http_model_meetplan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeetPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMeetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMeetPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMeetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMeetPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetPlansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetPlansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetPlanAndOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_model_meetplan_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetPlanAndOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_model_meetplan_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_model_meetplan_proto_goTypes,
		DependencyIndexes: file_http_model_meetplan_proto_depIdxs,
		EnumInfos:         file_http_model_meetplan_proto_enumTypes,
		MessageInfos:      file_http_model_meetplan_proto_msgTypes,
	}.Build()
	File_http_model_meetplan_proto = out.File
	file_http_model_meetplan_proto_rawDesc = nil
	file_http_model_meetplan_proto_goTypes = nil
	file_http_model_meetplan_proto_depIdxs = nil
}
