# Generated by Django 2.2.11 on 2020-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_auth', '0002_auto_20200401_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_graduate',
            field=models.BooleanField(choices=[(True, '研究生'), (False, '本科生')], verbose_name='研究生\\本科生'),
        ),
    ]
