# Generated by Django 2.2.5 on 2020-02-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0002_auto_20200212_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
