# Generated by Django 2.2.5 on 2020-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户详细信息', 'verbose_name_plural': '用户详细信息'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
