# Generated by Django 2.2.5 on 2020-02-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0004_auto_20200212_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='是否为管理员'),
        ),
    ]
