# Generated by Django 2.2.5 on 2020-02-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>@pku.edu.cn', help_text='电子邮件', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='是否为管理员, 管理员可登陆cmsadmin管理页面'),
        ),
    ]
