# Generated by Django 2.2.5 on 2020-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0006_auto_20200217_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='电子邮件', max_length=254, null=True),
        ),
    ]
