# Generated by Django 2.2.5 on 2020-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0008_auto_20200217_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default=None, upload_to='userprofile/headpicture'),
        ),
    ]
