# Generated by Django 2.2.5 on 2020-02-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0011_auto_20200221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='userprofile/headpicture/%Y/%m/%d/'),
        ),
    ]
