# Generated by Django 2.2.5 on 2020-02-23 14:50

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0012_auto_20200223_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default=None, null=True, storage=utils.storage.FileStorage(), upload_to='userprofile/headpicture/'),
        ),
    ]
