# Generated by Django 2.2.5 on 2020-02-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account_auth', '0013_auto_20200223_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_id',
            field=models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='职工号\\学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员, 管理员可登陆cmsadmin管理页面'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='是否为教职工'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CN', verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default=None, null=True, storage=utils.storage.FileStorage(), upload_to='userprofile/headpicture/', verbose_name='用户头像'),
        ),
    ]
