/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginLoader: typeof import('./src/components/animations/LoginLoader.vue')['default']
    MainAppBar: typeof import('./src/components/toolbar/MainAppBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolbarLanguage: typeof import('./src/components/toolbar/ToolbarLanguage.vue')['default']
    ToolbarUser: typeof import('./src/components/toolbar/ToolbarUser.vue')['default']
  }
}
