# Generated by Django 2.2.5 on 2020-02-11 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('place', models.CharField(help_text='谈话地点', max_length=128, verbose_name='谈话地点')),
                ('start_time', models.DateTimeField(help_text='谈话开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='谈话结束时间', verbose_name='结束时间')),
                ('allow_other', models.BooleanField(choices=[(0, '允许'), (1, '不允许')], help_text='是否可两人同时进行综合指导课', max_length=1, verbose_name='允许多人')),
                ('valid1', models.BooleanField(default=False)),
                ('valid2', models.BooleanField(default=False)),
                ('stu_id1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_id1', to=settings.AUTH_USER_MODEL)),
                ('stu_id2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_id2', to=settings.AUTH_USER_MODEL)),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '综合指导课',
                'verbose_name_plural': '综合指导课',
            },
        ),
    ]
