# Generated by Django 2.2.5 on 2020-02-17 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet_plan', '0002_auto_20200212_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetplan',
            name='tea_id',
        ),
        migrations.AddField(
            model_name='meetplan',
            name='teacher',
            field=models.ForeignKey(default=1600011378, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
