# Generated by Django 2.2.5 on 2020-02-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0003_auto_20200217_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetplanorder',
            old_name='meet_plan_id',
            new_name='meet_plan',
        ),
        migrations.RenameField(
            model_name='meetplanorder',
            old_name='stu_id',
            new_name='student',
        ),
    ]
