# Generated by Django 2.2.5 on 2020-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0004_auto_20200217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetplan',
            name='allow_other',
            field=models.BooleanField(choices=[(0, '允许'), (1, '不允许')], default=True, help_text='是否可两人同时进行综合指导课', max_length=1, verbose_name='允许多人'),
        ),
    ]
