# Generated by Django 2.2.5 on 2020-02-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0006_auto_20200222_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterdaterange',
            options={'verbose_name': '学期起止时间', 'verbose_name_plural': '学期起止时间'},
        ),
        migrations.RenameField(
            model_name='semesterdaterange',
            old_name='结束时间',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='semesterdaterange',
            old_name='开始时间',
            new_name='start_date',
        ),
    ]
