# Generated by Django 2.2.5 on 2020-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0008_auto_20200222_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetplan',
            name='available_choice',
            field=models.SmallIntegerField(default=2, verbose_name='还有多少名额'),
        ),
        migrations.AlterField(
            model_name='meetplan',
            name='allow_other',
            field=models.BooleanField(choices=[(0, '不允许'), (1, '允许')], default=True, help_text='是否可两人同时进行综合指导课', max_length=1, verbose_name='允许多人'),
        ),
    ]
