# Generated by Django 2.2.5 on 2020-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0009_auto_20200223_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetplanorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='意向谈话内容'),
        ),
    ]
