# Generated by Django 2.2.5 on 2020-02-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_plan', '0010_meetplanorder_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetplan',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
